config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Brain resource routes
  resources :brains do
    # Nested route for new reservations under a specific brain
    resources :reservations, only: [:new, :create]
  end

  # Reservation routes
  resources :reservations, only: [:show, :destroy, :edit, :update] do
    member do
      patch :accept
      patch :decline
    end
  end

  # # Notifications route for the current user
  # get '/users/notifications', to: 'users#index', as: 'user_notifications'
  resources :users, only: [:show]

  get "profile", to: "users#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brain.rb
class Brain < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :brain
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :brains
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  def index
    @brains = Brain.all
      if params[:query].present?
        @brains = Brain.where("specialty ILIKE ?", "%#{params[:query]}%")
      end


  end

  def show
    id = params[:id]
    @brain = Brain.find(id)
    @reservation = Reservation.new
    @brains = Brain.where(id:id)
    @markers = @brains.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end

  def new
    @brain = Brain.new
  end

  def create
    @brain = Brain.new(brain_params)
    @brain.user_id = current_user.id
    respond_to do |format|
      if @brain.save!
        format.html { redirect_to brain_path(@brain) }
        format.json
      else
        format.html { render "brains/new", status: :unprocessable_entity }
        format.json
      end
    end
  end

  def edit
    @brain = Brain.find(params[:id])
  end

  def update
    @brain = Brain.find(params[:id])
    @brain.update(brain_params)
    redirect_to brain_path(@brain)
  end

  def destroy
    @brain = Brain.find(params[:id])
    @brain.destroy
    redirect_to brains_path, status: :see_other
  end

  private

  def brain_params
    params.require(:brain).permit(:title, :specialty, :address, :photo, :description, :wiki_page, :price)
  end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def show
    @reservation = Reservation.find(params[:id])
    @reservations = Reservation.where(brain_id: @reservation.brain_id)
    @reservations = []
  end

  def new
    @brain = Brain.find(params[:brain_id])
    @reservation = Reservation.new
    @reservation.user_id = current_user.id
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    @reservation.brain_id = params[:brain_id]
    respond_to do |format|
      if @reservation.save!
        format.html { redirect_to reservation_path(@reservation) }
        format.json
      else
        format.html { render "reservations/new", status: :unprocessable_entity }
        format.json
      end
    end
  end

  def accept
    @reservation = Reservation.find(params[:id])
    @reservation.status = true # Or "accepted", if using a string
    if @reservation.save
      redirect_to profile_path(current_user), notice: 'Reservation accepted successfully.'
    else
      render :show, status: :unprocessable_entity
    end
  end

  def decline
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to profile_path(current_user)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  #   @notifications = Notification.all
  # end

  def show
    @user = User.find(params[:id])
    @brains = @user.brains
  end

  def profile
    @user = current_user
    @brains = Brain.where(user: @user)
    @reservations = []
    @brains.each do |brain|
      @reservations << Reservation.where(brain: brain)
    end
    @my_reservations = @user.reservations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brains/_form.html.erb
<%= simple_form_for brain,
  data: {
      insert_in_list_target: "form",
      action: "submit->insert-in-list#send"
    } do |f| %>
  <%= f.input :title %>
  <%= f.input :address %>
  <%= f.input :photo, as: :file %>
  <%= f.input :description %>
  <%= f.input :wiki_page %>
  <%= f.input :specialty %>
  <%= f.input :price %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/brains/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Mettre à jour un Brain</h1>
        <div class="mt-3">
          <%= render "form", brain: @brain %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/brains/index.html.erb
<div id="header">
  <div class="container" >
    <div class="search">
      <%= form_with url: brains_path, method: :get, class: "d-flex", id: "search-form" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Saisir une spécialité",
          id: "search-input"
        %>
        <%= submit_tag "Rechercher", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>

      <h1>Brains à louer</h1>
  </div>
</div>

<% if params[:query].blank? %>
  <div id="highlights" class="section">
    <div class="container">
      <h2>Top 3 recommandés</h2>
        <div class="cards">
          <% @brains.first(3).each do |brain| %>
            <%= link_to brain_path(brain) do %>
              <div class="grid-cell">
                <%= render "shared/brain_card", brain: brain %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
 <% end %>

<div id="all" class="section">
  <div class="container">
    <h2>Tous les Brains</h2>
    <% if @brains.any? %>
      <div class="cards">
        <% @brains.each do |brain| %>
          <%= link_to brain_path(brain) do %>
            <div class="grid-cell">
              <%= render "shared/brain_card", brain: brain %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% else %>
       <p class="no-result">Aucun résultat</p>
    <% end %>
  </div>
</div>



<div id="footer">

</div>

app/views/brains/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reservation Page</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="container-fluid main-container" style="background-color: black">
    <div class="row justify-content-center align-items-center gap-3">
      <div class="col" style="margin: 60px">
        <div class="card">
          <div class="card-header" style="background-color: black">
            <h1 class="card-title" style="color: white"><%= @brain.title %></h1>
          </div>
          <div class="card-body">
            <div class="card">
              <div style="width: 100%; height: 100%; position: relative">
                <% if @brain.photo.attached? %>
                  <%= cl_image_tag @brain.photo.key, height: "auto", style: "max-width:100%" %>
                <% end %>
              </div>
              <div class="card-body">
                <h5 class="card-title"><%= @brain.title %></h5>
                <div class="description" >
                  <div class="left">
                    <p class="card-text"><%= image_tag "euros.png", width:"3%"%> <%= @brain.price %> /jour</p>
                    <p class="card-text"><%= image_tag "brain.png", width:"3%"%> <%= @brain.specialty %></p>
                    <p class="card-text"><%= @brain.description %></p>
                  </div>
                  <div class="right">
                    <p class="card-text"><%= image_tag "home.png", width:"3%"%> <%= @brain.address %></p>
                    <div class="map"
                      data-controller="map"
                      data-map-markers-value="<%= @markers.to_json %>"
                      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
                    </div>
                  </div>
                </div>
                <a href="<%= @brain.wiki_page %>" style="color: black" target="_blank"><%= image_tag "wiki.png", width:"3%"%>  + d'infos</a>
              </div>
            </div>
          </div>
        </div>
      </div>
       <% unless current_user == @brain.user %>
      <div class="col" style="padding-top: 30px">
        <div class="reservation_container">
          <div class="h1">Faire une réservation</div>
          <div class="body_card_reservation">
            <div class="card_reservation">
              <div class = "header">
                <div class = "title"><%= @brain.title %></div>
                <div class = "subtitle">
                  <div class = "field_price">
                    <div class = "price"><%= @brain.price %>€ par jour</div>
                  </div>
                  <div class = "specialty">. <%= @brain.specialty %></div>
                </div>
              </div>
              <div class= "card_content">
                <%= render "reservations/form", reservation: @reservation, brain: @brain %>
              </div>
            </div>
            <div class = "legend">
              <div class = "content">
                <div class = "title">Safeguarded Interactions</div>
                <div class = "supporting_text">We value your privacy and the confidentiality of your projects. Rest assured, all interactions and exchanges are protected under strict NDAs and secure channels.</div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

      <% if current_user == @brain.user%>
        <div class="col" style="padding-top: 30px">
          <div class="row" style="padding-right: 60px">
              <%= link_to "Voir tous mes brains", profile_path, class: "nav-link text-white" %>
              <%= link_to "Update", edit_brain_path(@brain), class: "btn btn-primary me-md-2", type: "button" %>
             <%= link_to "Delete", brains_path(@brains), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger me-md-2", type: "button" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
    </div>


</body>
</html>

app/views/brains/show2.html.erb
<div class="card-trip">
  <% if @brain.photo.attached? %>
    <%= cl_image_tag @brain.photo.key %>
  <% end %>
  <div class="card-trip-infos">
    <div>
      <h2><%= @brain.title %> - <%= @brain.specialty %></h2>
      <p><%= @brain.description %></p>
      <p><%= @brain.address %></p>
      <p><%= link_to "#{@brain.user.first_name} #{@brain.user.last_name}", user_path(@brain.user) %></p>
      <p><%= link_to @brain.wiki_page, @brain.wiki_page %></p>
    </div>
    <h2 class="card-trip-pricing"><%= @brain.price %> €</h2>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= link_to "Back to the list", brains_path, class: "btn btn-secondary me-md-2", type: "button" %>
      <%= link_to "Make a Reservation", new_brain_reservation_path(@brain), class: "btn btn-primary me-md-2", type: "button" %>
      <%= link_to "Delete", brain_path(@brain), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-primary me-md-2", type: "button" %>
      <%= link_to "Update", edit_brain_path(@brain), class: "btn btn-primary me-md-2", type: "button" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<body>
  <div style="width: 100%; height: 100%; padding-left: 15px; padding-right: 15px; padding-top: 50px; padding-bottom: 50px; background: black; overflow: hidden; justify-content: center; align-items: center; gap: 60px; display: inline-flex">
    <div style="flex-direction: column; justify-content: center; align-items: center; gap: 35px; display: inline-flex">
      <div style="flex-direction: row; justify-content: space-between; align-items: center; gap: 30px; display: flex">
        <div style="height: 176.32px; padding-right: 37.27px; justify-content: flex-start; align-items: center; display: inline-flex">
          <div style="width: 150 px; height: 176.60px; position: relative; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
            <div style="width: 176.32px; height: 176.32px; padding-left: 27.57px; padding-right: 27.57px; justify-content: center; align-items: center; display: inline-flex">
              <div style="width: 121.18px; height: 176.32px; background: black">
                <%= image_tag "logo_blanc.png", class: "logo" %>
              </div>
            </div>
          </div>
        </div>
        <div style="color: white; font-size: 50.35px; font-family: Inter; font-weight: 700; word-wrap: break-word;">Need a brain?</div>
      </div>
      <div class="need-brain-container" style="padding-left: 80px; margin-top: 20px; text-align: left;">
        <div class="into" style="width: 734px; height: 102px; color: white; font-size: 20px; font-family: Inter; font-weight: 500; line-height: 41.60px; word-wrap: break-word;">Parfois, même les génies ont besoin d'un coup de main. Besoin d'une idée géniale pour un projet ? Ou peut-être juste quelqu'un pour résoudre ce problème de maths épineux ? Louez un cerveau sur Rent-A-Brain et transformez votre quotidien en une véritable révolution intellectuelle !</div>
      </div>
      <div style="padding-left: 35.09px; padding-right: 35.09px; padding-top: 10px; padding-bottom: 10px; background: radial-gradient(48.10% 3.54% at 48.10% 1.96%, #D33753 0%, #D13660 53%, #C72D65 100%); border-radius: 11.70px; border: 2.34px rgba(0, 0, 0, 0.12) solid; justify-content: center; align-items: center; gap: 23.40px; display: inline-flex; margin-top: 40px;">
        <%= link_to brains_path do %>
          <div style="color: white; font-size: 32.75px; font-family: Inter; font-weight: 600; line-height: 37.43px; letter-spacing: 2.92px; word-wrap: break-word; text-decoration: none;">Yes Please !</div>
        <% end %>
      </div>
    </div>
  </div>
  <div style="width: 100%; height: 100%; padding-top: 70px; padding-bottom: 96px; background: white; flex-direction: column; justify-content: flex-start; align-items: center; gap: 70px; display: inline-flex">
    <div style="height: 50px; padding-left: 32px; padding-right: 32px; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 45px; display: flex">
        <div style="align-self: stretch; height: 93px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 48px; display: flex">
            <div class="expertise" style="height: 93px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 20px; display: flex">
                <div style="align-self: stretch; text-align: center; color: #101828; font-size: 40px; font-family: Inter; font-weight: 700; line-height: 42.05px; word-wrap: break-word">Débloquez le pouvoir de l'expertise</div>
                <div class="harness" style="align-self: stretch; text-align: center; color: #667085; font-size: 20px; font-family: Inter; font-weight: 400; line-height: 30px; word-wrap: break-word">Tirez parti de la brillance dont vous avez besoin, quand vous en avez besoin.</div>
            </div>
        </div>
<%#         <div style="align-self: stretch; text-align: center; color: #101828; font-size: 28.03px; font-family: Inter; font-weight: 400; line-height: 42.05px; word-wrap: break-word"></div> %>
    </div>
    <div style="height: 640px; padding-left: 32px; padding-right: 32px; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 64px; display: flex">
        <div style="align-self: stretch; justify-content: center; align-items: center; gap: 50px; display: inline-flex">
            <div style="flex: 1 1 0; flex-direction: column; justify-content: flex-start; align-items: center; gap: 35px; display: inline-flex">
                <div style="width: 48px; height: 48px; padding: 12px; background: #F4EBFF; border-radius: 28px; border: 8px #F9F5FF solid; justify-content: center; align-items: center; display: inline-flex">
                    <div style="width: 24px; height: 24px; position: relative; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
                        <div style="width: 20.90px; height: 18.23px"><%= image_tag "heart.jpg" %></div>
                    </div>
                </div>
                <div style="align-self: stretch; height: 205px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 15px; display: flex">
                    <div style="align-self: stretch; text-align: center; color: #101828; font-size: 25px; font-family: Inter; font-weight: 600; line-height: 30px; word-wrap: break-word">Expertise Diversifiée</div>
                    <div style="align-self: stretch; text-align: center; color: #475467; font-size: 20px; font-family: Inter; font-weight: 400; line-height: 40px; word-wrap: break-word">Plongez dans notre vaste bassin d'intellects provenant de différents domaines - science, technologie, ingénierie, arts et mathématiques. Nos cerveaux sont équipés d'années d'expérience, prêts à infuser vos projets d'idées et d'aperçus innovants.</div>
                </div>
            </div>
            <div style="flex: 1 1 0; flex-direction: column; justify-content: flex-start; align-items: center; gap: 35px; display: inline-flex">
                <div style="width: 48px; height: 48px; padding: 12px; background: #F4EBFF; border-radius: 28px; border: 8px #F9F5FF solid; justify-content: center; align-items: center; display: inline-flex">
                    <div style="width: 24px; height: 24px; position: relative; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
                        <div style="width: 20.90px; height: 18.23px"><%= image_tag "heart.jpg" %></div>
                    </div>
                </div>
                <div style="align-self: stretch; height: 205px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 15px; display: flex">
                    <div style="align-self: stretch; text-align: center; color: #101828; font-size: 25px; font-family: Inter; font-weight: 600; line-height: 30px; word-wrap: break-word">Engagements Flexibles</div>
                    <div style="align-self: stretch; text-align: center; color: #475467; font-size: 20px; font-family: Inter; font-weight: 400; line-height: 40px; word-wrap: break-word">Choisissez comment vous collaborez. Engagez-vous avec les principaux penseurs sur une base de projet, programmez des séances de remue-méninges, ou bénéficiez d'une consultation continue. Avec Rent a Brain, l'expertise intellectuelle est disponible selon vos conditions.</div>
                </div>
            </div>
        </div>
        <div style="align-self: stretch; justify-content: flex-start; align-items: flex-start; gap: 32px; display: inline-flex">
            <div style="flex: 1 1 0; flex-direction: column; justify-content: flex-start; align-items: center; gap: 35px; display: inline-flex">
                <div style="width: 48px; height: 48px; padding: 12px; background: #F4EBFF; border-radius: 28px; border: 8px #F9F5FF solid; justify-content: center; align-items: center; display: inline-flex">
                    <div style="width: 24px; height: 24px; position: relative; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
                        <div style="width: 20.90px; height: 18.23px"><%= image_tag "heart.jpg" %></div>
                    </div>
                </div>
                <div style="align-self: stretch; height: 205px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 15px; display: flex">
                    <div style="align-self: stretch; text-align: center; color: #101828; font-size: 25px; font-family: Inter; font-weight: 600; line-height: 30px; word-wrap: break-word">Collaboration Fluide</div>
                    <div style="align-self: stretch; text-align: center; color: #475467; font-size: 20px; font-family: Inter; font-weight: 400; line-height: 40px; word-wrap: break-word">Notre plateforme est conçue pour faciliter l'interaction fluide entre vous et l'expert que vous avez choisi. Avec des outils de communication intuitifs et des capacités de partage de ressources, la collaboration n'a jamais été aussi simple.</div>
                </div>
            </div>
            <div style="flex: 1 1 0; flex-direction: column; justify-content: flex-start; align-items: center; gap: 35px; display: inline-flex">
                <div style="width: 48px; height: 48px; padding: 12px; background: #F4EBFF; border-radius: 28px; border: 8px #F9F5FF solid; justify-content: center; align-items: center; display: inline-flex">
                    <div style="width: 24px; height: 24px; position: relative; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
                        <div style="width: 20.90px; height: 18.23px"><%= image_tag "heart.jpg" %></div>
                    </div>
                </div>
                <div style="align-self: stretch; height: 165px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 15px; display: flex">
                    <div style="align-self: stretch; text-align: center; color: #101828; font-size: 25px; font-family: Inter; font-weight: 600; line-height: 30px; word-wrap: break-word">Interactions Sécurisées</div>
                    <div style="align-self: stretch; text-align: center; color: #475467; font-size: 20px; font-family: Inter; font-weight: 400; line-height: 40px; word-wrap: break-word">Nous attachons de l'importance à votre vie privée et à la confidentialité de vos projets. Soyez assuré que toutes les interactions et les échanges sont protégés par des accords de confidentialité stricts et des canaux sécurisés.</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="width: 100%; height: 100%; padding-top: 25px; padding-bottom: 70px; padding-left: 80px; padding-right: 80px; background: white; flex-direction: column; justify-content: center; align-items: center; gap: 43px; display: inline-flex">
<div style="width: 1250px; height: 398.82px; padding-left: 32px; padding-right: 32px; padding-top: 40px; padding-bottom: 40px; background: #F9FAFB; box-shadow: 0px 6px 16px rgba(0, 0, 0, 0.12); border-radius: 16px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 32px; display: flex">
<div style="align-self: stretch; height: 318.82px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 28.03px; display: flex">
<div style="align-self: stretch; height: 231px; flex-direction: column; justify-content: flex-start; align-items: center; gap: 28px; display: flex">
<div style="align-self: stretch; text-align: center; color: #101828; font-size: 33.64px; font-family: Inter; font-weight: 700; line-height: 42.05px; word-wrap: break-word">Vous avez un brain à louer? </div>
<div style="align-self: stretch; text-align: center; color: #101828; font-size: 28.03px; font-family: Inter; font-weight: 400; line-height: 42.05px; word-wrap: break-word">Pourquoi attendre que l'inspiration frappe ou que l'expertise se développe en interne lorsque vous pouvez louer un cerveau et accélérer votre progression dès maintenant ? Chez Rent a Brain, vos objectifs sont à portée de main. Faisons de la brillance un atout accessible et de votre succès inévitable.</div>
</div>
<%= link_to new_brain_path do %>
<div style="padding-left: 24.59px; padding-right: 24.59px; padding-top: 16.40px; padding-bottom: 16.40px; background: radial-gradient(48.10% 3.54% at 48.10% 1.96%, #D33753 0%, #D13660 53%, #C72D65 100%); border-radius: 8.20px; border: 1.64px rgba(0, 0, 0, 0.12) solid; justify-content: center; align-items: center; gap: 16.40px; display: inline-flex">
<div style="color: white; font-size: 22.95px; font-family: Inter; font-weight: 600; line-height: 26.23px; letter-spacing: 2.05px; word-wrap: break-word">Louer mon brain</div>
<% end %>
</div>
</div>
</div>
</div>

</body>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background: black; margin-bottom: 1px;">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <div class="d-flex align-items-center">
        <%= image_tag "logo_blanc.png", width:"20%"%>
        <h1 style="color: white; font-size: 27.30px; font-family: Inter; font-weight: 900; margin-left: 10px;">Rent a brain</h1>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Trouver un brain", brains_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Louer son brain", new_brain_path, class: "nav-link text-white" %>
          </li>
           <li class="nav-item">
            <%= link_to "Profil", profile_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link text-white" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div style="background-color: black; width: 100%; height: 100%; display: flex;">
    <!-- Colonne de gauche -->
    <div style="flex: 1; padding: 25px;">
        <div style="flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 10px;">
            <h3 style="color: white;">Demandes de réservation reçues</h3>
            <div id="reservations" style="color: white;">
                <ul>
                    <% @reservations.flatten.each do |reservation| %>
                        <li>
                            <%= cl_image_tag reservation.brain.photo.key, color: "white", width: 50, height: 50, gravity: "face", crop: "thumb" %> <%= reservation.brain.title %>
                            <% if reservation.status == false %>
                                <p>En attente</p>
                                <%= button_to "Accepter", accept_reservation_path(id: reservation), method: :patch %>
                                <%= button_to "Refuser", decline_reservation_path(id: reservation), method: :patch %>
                            <% else %>
                                <p>Reservation acceptée</p>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </div>


            <h3 style="color: white;">Demandes de réservation envoyées</h3>
            <ul>
                <% @my_reservations.each do |my_reservation| %>
                    <li><%= cl_image_tag my_reservation.brain.photo.key, width: 50, height: 50, gravity: "face", crop: "thumb" %> <%= my_reservation.brain.title %></li>
                <% end %>
            </ul>
        </div>
    </div>

    <!-- Colonne de droite -->
    <div style="flex: 1; padding: 25px; background-color:black; color: white">
        <div class="container">
            <h2>Vos brains</h2>
            <% if @brains.any? %>
                <div class="cards">
                    <% @brains.each do |brain| %>
                        <%= link_to brain_path(brain) do %>
                            <div class="grid-cell">
                                <%= render "shared/brain_card", brain: brain %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            <% else %>
                <p class="no-result">Aucun résultat</p>
            <% end %>
        </div>
    </div>
</div>